export const POST_STARTINTERVIEW_LOADING = 'POST_STARTINTERVIEW_LOADING';
export const POST_STARTINTERVIEW_ERROR = 'POST_STARTINTERVIEW_ERROR';
export const POST_STARTINTERVIEW_SUCCESS = 'POST_STARTINTERVIEW_SUCCESS';

export const PATCH_ANSWER_LOADING = 'PATCH_ANSWER_LOADING';
export const PATCH_ANSWER_ERROR = 'PATCH_ANSWER_ERROR';
export const PATCH_ANSWER_SUCCESS = 'PATCH_ANSWER_SUCCESS';

export const POST_ENDINTERVIEW_LOADING = 'POST_ENDINTERVIEW_LOADING';
export const POST_ENDINTERVIEW_ERROR = 'POST_ENDINTERVIEW_ERROR';
export const POST_ENDINTERVIEW_SUCCESS = 'POST_ENDINTERVIEW_SUCCESS';

export const CHANGE_INTERVIEW_TYPE= 'CHANGE_INTERVIEW_TYPE';