export const POST_CREATEUSER_LOADING = "POST_CREATEUSER_LOADING";
export const POST_CREATEUSER_ERROR = "POST_CREATEUSER_ERROR";
export const POST_CREATEUSER_SUCCESS = "POST_CREATEUSER_SUCCESS";

export const POST_LOGIN_LOADING = "POST_LOGIN_LOADING";
export const POST_LOGIN_ERROR = "POST_LOGIN_ERROR";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";

export const GET_LOGOUT_LOADING = "GET_LOGOUT_LOADING";
export const GET_LOGOUT_ERROR = "GET_LOGOUT_ERROR";
export const GET_LOGOUT_SUCCESS = "GET_LOGOUT_SUCCESS";

export const GET_LOGGEDUSER_LOADING = "GET_LOGGEDUSER_LOADING";
export const GET_LOGGEDUSER_ERROR = "GET_LOGGEDUSER_ERROR";
export const GET_LOGGEDUSER_SUCCESS = "GET_LOGGEDUSER_SUCCESS";

export const PATCH_LOGGEDUSER_SUCCESS = "PATCH_LOGGEDUSER_SUCESS";

export const GET_USERINTERVIEWS_LOADING = "GET_USERINTERVIEWS_LOADING";
export const GET_USERINTERVIEWS_ERROR = "GET_USERINTERVIEWS_ERROR";
export const GET_USERINTERVIEWS_SUCCESS= "GET_USERINTERVIEWS_SUCCESS"; 

export const UPDATE_USER_LOADING = "UPDATE_USER_LOADING";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const GET_LEADERBOARD_LOADING = "GET_LEADERBOARD_LOADING";
export const GET_LEADERBOARD_ERROR = "GET_LEADERBOARD_ERROR";
export const GET_LEADERBOARD_SUCCESS = "GET_LEADERBOARD_SUCCESS";

